### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by jgoz** [appleboy/jquery-migrate#4]
Now that `bower.json` has a `main` property, can you please bump the version number for this project? The latest version in Bower is outdated (doesn't have `main`).

The property helps integration with browserify & webpack, but in order to use it we have to target the hash for the current master.

**Comment by nikolaik** [comment]
+1

**Comment by jkeylu** [comment]
+1

**Comment by appleboy** [comment]
Hi all,

I already update jquery-migrate to 1.3.0. You can download it via bower command now.

Thanks for your friendly reminder.
