### ISSUE TITLE
Version 3.0

### ISSUE THREAD

**Issue by aiphee** [appleboy/jquery-migrate#6]
Version 3.0 is out, could you update it?

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
Closed via #7

**Comment by forstjiri** [comment]
Perfect, could you also make a release so it can be installed via bower?

**Comment by appleboy** [comment]
@aiphee Done.

https://github.com/appleboy/jquery-migrate/releases/tag/3.0.0

**Comment by forstjiri** [comment]
@appleboy wow, that was fast, thank you :)
